### PR TITLE
Added app.src.

### PR DESCRIPTION
**Pull request by oubiwann**
When trying to use esdl2 from LFE, I was getting errors due to the lack of an app.src file.

Not sure how you usually handle this ... auto-generate it maybe?

### CODE REVIEW

**Comment by essen** [comment]
The auto generated file is the .app file and you're right it's missing, it should be committed (possibly after upgrading Erlang.mk). The .app.src file has no reason to be there though.

**Comment by oubiwann** [comment]
/me nods

LFE  projects tend to put the app.src in the ``/src`` dir since rebar3 "compiles" it to the project's ``ebin`` directory ... whatever you end up doing, though, we'll find a way to use it :-)

**Comment by essen** [comment]
Rebar can use the .app just as fine and it's standard. Erlang.mk can generate it completely without the user having to touch a .app.src file. Therefore we should have a .app file, not .app.src.

**Comment by oubiwann** [comment]
Just updated it with the generated one.

**Comment by essen** [comment]
Someone has sent both this and a rebar.config for rebar3, closing this then, thanks!

**Pull request closed without merging**
