### PR TITLE
c opts for Mac

### PR DESCRIPTION
**Pull request by hdiedrich**
for newest master

### CODE REVIEW

**Comment by essen** [comment]
@wmealing Do you know if this is required for all shared libs used as NIF or just because of something related to SDL2? Should it be the default in Erlang.mk?

**Comment by essen** [comment]
OSX should work fine out of the box now. Closing, thanks!

**Comment by wmealing** [comment]
Sorry, somehow missed the notification.. all libs afaics.

**Comment by essen** [comment]
Yes that should be fixed for all libs. :-)

**Pull request closed without merging**
